# Generated by Django 3.0.3 on 2020-05-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summarize',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('text', models.TextField(default='', max_length=15000)),
                ('summarize', models.TextField(default='', max_length=10000)),
            ],
        ),
    ]
