# Generated by Django 3.0.6 on 2020-05-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarize',
            name='summarize',
            field=models.TextField(default='', max_length=15000),
        ),
        migrations.AlterField(
            model_name='summarize',
            name='text',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
